version: '3.8'

services:
  ahmapi-dev:
    container_name: ahmapi-server-dev
    ports:
      - '8086:8080'
    build:
      context: .
      cache_from:
        - amazoncorretto:17
      dockerfile: Dockerfile
    image: ahmapi-dev:${BUILD_DATE}
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - XMS=${START_JAVA_HEAP_SIZE}
      - XMX=${MAX_JAVA_HEAP_SIZE}
    depends_on:
      mysqldb:
        condition: service_healthy
      phpmyadmin:
        condition: service_healthy
      fakemail:
        condition: service_healthy
  mysqldb:
    image: mysql:8.0.32
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=airhub_db
    healthcheck:
      test: "mysqladmin ping -u root -p$root"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysqldb
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - '6061:80'
    healthcheck:
      test: "exit 0"
  fakemail:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    healthcheck:
      test: "exit 0"
