server:
  port: 8085

spring:
  h2.console.enabled: false
  liquibase:
    drop-first: false
    contexts: lq_prod
    database-change-log-lock-table: _liquibase_changelog_lock
    database-change-log-table: _liquibase_changelog
  datasource:
    url: ${PROD_DB_JDBC}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    protocol: smtp
    port: 465
    host: ${PROD_SMTP_MAIL_SERVER}
    username: ${PROD_SMTP_MAIL_USERNAME}
    password: ${PROD_SMTP_MAIL_PASSWORD}
    properties:
      smtp.starttls.required: true
      mail.smtp:
        ssl.enable: true
        auth: true
        starttls.enable: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

jmpsl:
  security:
    jwt:
      secret: ${PROD_JWT_SECRET}

api:
  mail-responder: ${PROD_SMTP_MAIL_USERNAME}
