spring:
  h2.console.enabled: false
  liquibase:
    drop-first: false
    contexts: lq_dev
    database-change-log-lock-table: _liquibase_changelog_lock
    database-change-log-table: _liquibase_changelog
  datasource:
    url: jdbc:mysql://mysqldb:3306/airhub_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    protocol: smtp
    port: 1025
    host: 127.0.0.1
    username: ''
    password: ''
    properties:
      smtp.starttls.required: false
      mail.smtp:
        ssl.enable: false
        auth: false
        starttls.enable: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

jmpsl:
  security:
    jwt:
      secret: h64h3hbntohbjk50rp9hgkj03gormgobrwnmgoriwjmhgoithjkgo

api:
  mail-responder: DEVELOPMENT@airhubmaster.com
