server:
  port: 8081

spring:
  devtools:
    livereload:
      port: 35731
    restart:
      log-condition-evaluation-delta: false
  h2:
    console:
      enabled: true
  liquibase:
    contexts: lq_dev
    drop-first: false
  datasource:
    url: jdbc:h2:file:./h2-db
    username: dbuser
    password: dbpass
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  mail:
    protocol: smtp
    port: 1025
    host: 127.0.0.1
    username: ''
    password: ''
    properties:
      smtp.starttls.required: false
      mail.smtp:
        ssl.enable: false
        auth: false
        starttls.enable: false

jmpsl:
  security:
    jwt:
      secret: h64h3hbntohbjk50rp9hgkj03gormgobrwnmgoriwjmhgoithjkgo

api:
  mail-responder: DEVELOPMENT@airhubmaster.com
