#!/bin/bash
#
# Copyright (c) 2023 by MILOSZ GILGA <https://miloszgilga.pl>
# Silesian University of Technology
#

lang_dir="../src/main/resources"
sample_lang_file_name="messages_en.properties"

api_lang_prefix="i18n-api"
jpa_lang_prefix="i18n-jpa"
mail_lang_prefix="i18n-mail"

lang_prefixes=("$api_lang_prefix" "$jpa_lang_prefix" "$mail_lang_prefix")

arg_key="--lang"
is_arg_not_exist=false

if [ "$#" -eq 0 ]; then
  is_arg_not_exist=true
fi

IFS="=" read -r key value <<<"$@"
if [ "$key" == "$arg_key" ]; then
  output_file_name="messages_$value.properties"
else
  is_arg_not_exist=true
fi

if [ $is_arg_not_exist == true ]; then
  echo "[bash gen script err] <> Available only argument: --lang=<i18n tag>"
  exit 1
fi

for ((i = 0; i < ${#lang_prefixes[@]}; i++)); do
  base_prefix=$lang_dir/${lang_prefixes[$i]}

  if [ ! -d "$base_prefix" ]; then
    echo "[bash gen script err] <> Directory '$base_prefix' not exist in /resources project context"
    exit 2
  fi
  if [ ! -f "$base_prefix/$sample_lang_file_name" ]; then
    echo "[bash gen script err] <> Sample file '$sample_lang_file_name' not exist in '$base_prefix' directory"
    exit 3
  fi
  if [ -f "$lang_dir/${lang_prefixes[$i]}/$output_file_name" ]; then
    echo "[bash gen script err] <> Lang file '$output_file_name' already exist in '$base_prefix' directory"
    exit 4
  fi
done

for ((i = 0; i < ${#lang_prefixes[@]}; i++)); do
  output_path="$lang_dir/${lang_prefixes[$i]}/$output_file_name"

  touch "$output_path"
  {
    echo "# Generated by: ${0##*/}, $(date +"%D %T")"
    echo "# Bash interpreter version: ${BASH_VERSION}"
    echo
    echo -n "# $output_file_name"
  } >>"$output_path"

  while IFS= read -r line; do
    if [[ $line =~ ^#.* ]]; then
      continue
    fi
    IFS="=" read -r key value <<<"$line"
    if [ -z "$line" ]; then
      echo "$key" >>"$output_path"
    else
      echo "$key=" >>"$output_path"
    fi
  done <"$lang_dir/${lang_prefixes[$i]}/$sample_lang_file_name"

  echo "[bash gen script info] <> Output lang file '$output_path' was successfully generated"
done
